baseURL = "http://localhost:1313/PTEROSOR_endofterm_workshop/"
#baseURL = "https://lcpq.github.io/PTEROSOR_endofterm_workshop/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "2nd WORKSHOP ON EXCITED-STATE METHODS (Toulouse, 8-10 Apr 2025)"
[Params]
  hometitle = "EMERGING EXCITED-STATE METHODS IN ELECTRONIC STRUCTURE"
  logo="img/PTEROSOR.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/conf.jpg"
  desc = "2nd WORKSHOP ON EXCITED-STATE METHODS"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
   name = "PTEROSOR"
   email = "loos@irsamc.ups-tlse.fr"
   github = "pfloos"
   twitter = "PTEROSOR"
   youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Program"
    url = "planning"
    weight = 2

 [[menu.main]]
     name="Posters"
     url = "posters"
     weight = 3

[[menu.main]]
    name = "Location"
    url = "map"
    weight = 4

[[menu.main]]
    name = "Participants"
    url = "participants"
    weight = 5

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 6

