baseURL = "http://localhost:1313/PTEROSOR_midterm_workshop/"
#baseURL = "https://pfloos.github.io/PTEROSOR_midterm_workshop/"
canonifyurls  = true
languageCode = "en-us"
DefaultContentLanguage = "en"
theme = "beautifulhugo"
title = "WORKSHOP ON EXCITED-STATE METHODS (Toulouse, 4-6 Apr 2023)"
[Params]
  hometitle = "WORKSHOP ON EXCITED-STATE METHODS"
  logo="img/PTEROSOR.png"
#  subtitle = ""
[[Params.bigimg]]
  src = "img/banner.png"
  desc = "WORKSHOP ON EXCITED-STATE METHODS"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 [Author]
   name = "PTEROSOR"
   email = "loos@irsamc.ups-tlse.fr"
   github = "pfloos"
   twitter = "PTEROSOR"
   youtube = "channel/UCPUtUMqEM3K5sYcMJGTd_Bg"

[[menu.main]]
    name = "Home"
    url = ""
    weight = 1

[[menu.main]]
    name = "Registration"
    url = "registration"
    weight = 2

[[menu.main]]
    name = "Planning"
    url = "planning"
    weight = 3

 [[menu.main]]
     name="Presentations"
     url = "presentations"
     weight = 4

 [[menu.main]]
     name="Posters"
     url = "posters"
     weight = 5

[[menu.main]]
    name = "Location"
    url = "map"
    weight = 6

[[menu.main]]
    name = "Participants"
    url = "participants"
    weight = 7

[[menu.main]]
    name = "Sponsors"
    url = "sponsors"
    weight = 8

#[[menu.main]]
#    parent="external"
#    name = "CNRS"
#    url = "http://www.cnrs.fr"
#    weight = 2

